### ISSUE TITLE
Error when cleaning/sorting the reagent bank

### ISSUE THREAD

**Issue by cremor** [gsnerf/Baud-Bag#5]
The following error is thrown when I use the feature to clean/sort the reagent bank:

```
12x Interface/AddOns/BaudBag/BaudBag.lua:95: attempt to index local 'containerItemInfo' (a nil value)
[string "@Interface/AddOns/BaudBag/BaudBag.lua"]:95: in function `?'
[string "@Interface/AddOns/BaudBag/BaudBag.lua"]:317: in function <Interface/AddOns/BaudBag/BaudBag.lua:314>
[string "=[C]"]: in function `func'
[string "@Interface/SharedXML/UIDropDownMenu.lua"]:1007: in function `UIDropDownMenuButton_OnClick'
[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1: in function <[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1>
```

Baud Bag v10.0.2.5 on WoW 10.0.2

**Comment by gsnerf** [comment]
Should be fixed with bb2920200026a6ed4d108f71863ec90429c34b98 and make it's way into `10.0.2.7`

**Comment by cremor** [comment]
I still get this error with v10.0.2.7.

New stack trace/line numbers:
```
12x Interface/AddOns/BaudBag/BaudBag.lua:101: attempt to index local 'containerItemInfo' (a nil value)
[string "@Interface/AddOns/BaudBag/BaudBag.lua"]:101: in function `?'
[string "@Interface/AddOns/BaudBag/BaudBag.lua"]:333: in function <Interface/AddOns/BaudBag/BaudBag.lua:330>
[string "=[C]"]: in function `func'
[string "@Interface/SharedXML/UIDropDownMenu.lua"]:1007: in function `UIDropDownMenuButton_OnClick'
[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1: in function <[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1>

```

**Comment by gsnerf** [comment]
Can ypu please try to open the option window once and reload the UI? I have encountered a strange configuration state on one of ly toons which was fixed by this.

**Comment by cremor** [comment]
I still get the error after doing that.

**Comment by cremor** [comment]
Fixed in v10.0.2.8, thanks.
